import requests
import json
import sys
import os

def run_mock_webhook():
    review_url = "http://127.0.0.1:8000/review"
    patch_url = "http://127.0.0.1:8000/apply-fix"
    
    # 1. Create a local target test file with flawed code (Test Case 3: Spaghetti & Bad Naming)
    test_file_path = "test_bad_code.py"
    
    bad_code = '''
def verify_status_code(code: int) -> str:
    """
    Translates HTTP status codes to readable messages.
    """
    # IDENTITY comparison on integer literals (Highly Unsafe!)
    if code is 200:
        return "SUCCESS"
    elif code is 500:
        return "INTERNAL_SERVER_ERROR"
        
    return "UNKNOWN"

'''

    with open(test_file_path, "w", encoding="utf-8") as f:
        f.write(bad_code)
        
    print("CodeGuardian AI - Auto-Fix & Patching Verification Test")
    print(f"1. Created test file: {test_file_path} with bad code.")
    print("-" * 50)
    
    payload = {
        "file_path": test_file_path,
        "code_content": bad_code,
        "diff_content": "+ def fetch_user_record(username: str) -> list:"
    }
    
    try:
        # Trigger review
        print("2. Submitting file for multi-agent graph review...")
        response = requests.post(review_url, json=payload, timeout=60)
        if response.status_code != 200:
            print(f"Error: Server returned error status {response.status_code}: {response.text}")
            return
            
        result = response.json()
        print("Review completed successfully!")
        print(f"File reviewed: {result['file_reviewed']}")
        print(f"Static issues found by scanners: {result['static_issues_count']}")
        
        # Save markdown report
        report_path = "review_report.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(result["final_report"])
        print(f"Unified Agent Review Report saved to: {report_path}")
        print("-" * 50)
        
        # 3. Retrieve proposed fixes
        fixes = result.get("proposed_fixes", [])
        print(f"3. Received {len(fixes)} auto-fix proposal(s) from LLM.")
        
        if not fixes:
            print("No auto-fixes generated by agents. Check LLM rate limits or prompt rules.")
            return
            
        # 4. Apply each proposed patch autonomously via the server endpoint!
        for idx, fix in enumerate(fixes):
            desc = fix.get("description", "Refactor change")
            orig = fix.get("original_code")
            corr = fix.get("corrected_code")
            
            if not orig or not corr:
                continue
                
            print(f"\nApplying Fix {idx + 1}: {desc}...")
            
            patch_payload = {
                "file_path": test_file_path,
                "original_code": orig,
                "corrected_code": corr
            }
            
            patch_resp = requests.post(patch_url, json=patch_payload)
            if patch_resp.status_code == 200:
                print(f"Fix {idx + 1} applied successfully!")
            else:
                print(f"Failed to apply Fix {idx + 1}: {patch_resp.text}")
                
        print("-" * 50)
        # 5. Read and print the corrected file contents to show success
        print("4. Inspecting corrected file contents on disk:")
        print("-" * 50)
        with open(test_file_path, "r", encoding="utf-8") as f:
            print(f.read())
        print("-" * 50)
        print("End-to-End Auto-Fix application test completed successfully!")
        
    except requests.exceptions.ConnectionError:
        print("Connection Error: Ensure CodeGuardian AI server is running (run 'python run.py' first).")
        # Cleanup temp file on connection exit
        if os.path.exists(test_file_path):
            os.remove(test_file_path)
        sys.exit(1)

if __name__ == "__main__":
    run_mock_webhook()
